# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HTTPMockDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'

  # Pods for HTTPMockDemo

end

target 'HTTPMocks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for HTTPMocks

  target 'HTTPMocksTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
